package provider

const sliceStringProp string = "slice_string"
const extraTokensProp string = "extra_tokens"
const defaultLocationProp string = "default_location"
const defaultResourceNameFormatProp string = "default_resource_name_format"
const defaultNodashNameFormatProp string = "default_nodash_name_format"
const defaultGlobalResourceNameFormatProp string = "default_global_resource_name_format"
const defaultGlobalNodashNameFormatProp string = "default_global_nodash_name_format"
const azureResourceFormatsProp string = "azure_resource_formats"
const customResourceFormatsProp string = "custom_resource_formats"
const nameProp string = "name"
const typeProp string = "type"
const locationProp string = "location"
const resultProp string = "result"
