package provider

const sliceStringProp string = "slice_string"
const extraTokensProp string = "extra_tokens"
const defaultLocationProp string = "default_location"
const defaultResourceNameFormatProp string = "default_resource_name_format"
const defaultNodashNameFormatProp string = "default_nodash_name_format"
const resourceFormatsProp string = "resource_formats"
const nameProp string = "name"
const typeProp string = "type"
const locationProp string = "location"
const resultProp string = "result"
const sqlServerDnsProp string = "sql_server_dns"
const databaseProp string = "database"
const accountNameProp string = "account_name"
const portProp string = "port"
const objectIdProp string = "object_id"
const accountTypeProp string = "account_type"
const roleProp string = "role"
